permalink: /:title/
relative_permalinks: false
future: false
collections:
  notes:
    output: true
    permalink: /:title/
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: basics
    values:
      layout: basics
  -
    scope:
      path: tables
    values:
      layout: tables
  -
    scope:
      path: layout
    values:
      layout: layout
